---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at <https://ds202-at-isu.github.io/labs.html> for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.

All submissions to the github repo will be automatically uploaded for grading once the due date is passed. Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

### Step 12.1

Chai's Note: I already linked my Git account.

Kyle's Notes:

- I already had everything installed, so I ran into no issues there.

Mariana's Notes:

- I already had Git installed, so I did not have any issues.

Nick's Notes:
- Git installed already

### Step 12.2
Chai's Note: The repository already created by the instructor so no issues found. 

Kyle's Notes:

- I had no issues connecting to my team's repo through github classroom.

Mariana's Notes:

- I did not have any issues connecting with my team's repo.

Nick's Notes:
- No issues connecting

### Step 12.3
Chai's Note: I have cloned the test GitHub repository to my computer via RStudio and there were no-issues in doing that.

Kyle's Notes:

- I had no issues cloning the repo onto my machine.

Mariana's Notes:

- I did not have any issues cloning the repo to my computer.


Nick's Notes:
- No issues cloning

### Step 12.4
Chai's Note: This is from R studio. There was an issue with branches, which is fixed now.

Kyle's Notes:

- *This is a line from RStudio.*
- I did not have any issues saving & committing my changes.
- I was also able to knit my changes to the .Rmd file and it saved them in the .md file too.

Nick's note:
- A merge commit and merge conflict resolve was necessary since multiple team members were working on the same branch

Mariana's Notes:

- This is a line from RStudio.
- I had some issues commiting my changes because it did not recognize my email, so I had to configure my email on git, and then I was able to commit.
  
### Step 12.5
Chai's Note: I did not have any issues pushing the changes.

Kyle's Notes:

- I did not have any issues pushing my local changes to GitHub.

Mariana's Notes:

- I had some issues pushing the changes because I did not have the updated version of the files, so I had to pull before pushing my local changes.

Nick's Notes: No issues pushing once merge conflict was resolved

### Step 12.6
Kyle's Notes:

- I did not have any issues viewing my changes on the GitHub Repo website.

Mariana's Notes:

- After pushing, I was able to see my changes on the GitHub Repo website.

Nick's Notes: Confirm all changes are visible on the github repo.

### Step 12.7
Kyle's Notes:

- Did not do this step as stated in the lab instructions.

Mariana's Notes:

- Step ignored, as per lab instructions.
